"""Consolidated primary-statement layout; amounts in INR millions."""

ASSETS_NC = (
    "ppe",
    "intangibles",
    "associates",
    "investments",
    "ar_nc",
    "ofa_nc",
    "dta",
    "tax_assets",
)
ASSETS_C = (
    "inventories",
    "ar_current",
    "cash",
    "other_bank",
    "loans",
    "ofa_current",
    "other_current_assets",
)
EQUITY = ("share_capital", "premium", "reserves", "application_money", "nci")
LIAB_NC = (
    "debt_nc",
    "lease_nc",
    "ap_nc",
    "ofl_nc",
    "provisions_nc",
    "other_liabilities_nc",
)
LIAB_C = (
    "debt_current",
    "lease_current",
    "ap_msme",
    "ap_other",
    "ofl_current",
    "other_liabilities_current",
    "provisions_current",
    "tax_liabilities",
)
BS_KEYS = ASSETS_NC + ASSETS_C + EQUITY + LIAB_NC + LIAB_C
OP_ASSETS = (
    "ar_nc",
    "ofa_nc",
    "inventories",
    "ar_current",
    "ofa_current",
    "other_current_assets",
)
OP_LIABS = (
    "ap_nc",
    "ofl_nc",
    "provisions_nc",
    "other_liabilities_nc",
    "ap_msme",
    "ap_other",
    "ofl_current",
    "other_liabilities_current",
    "provisions_current",
)
EXPENSES = (
    "cost_sales",
    "inventory_change",
    "employees",
    "finance_cost",
    "da",
    "other_expenses",
)
CF_ADJUSTMENTS = (
    "da",
    "associates_adj",
    "unrealized_fx",
    "bad_debt",
    "credit_writeback",
    "asset_sale_gain",
    "subsidiary_sale_gain",
    "esop",
    "lease_interest",
    "borrowing_interest",
    "investment_income",
    "provision_contracts",
    "provision_employee",
    "provision_damages",
    "provision_warranty",
)
CF_WC = (
    "wc_receivables",
    "wc_ofa",
    "wc_other_assets",
    "wc_inventory",
    "wc_payables",
    "wc_ofl",
    "wc_other_liabilities",
    "wc_provisions",
)
CF_INVEST = (
    "capex",
    "asset_sale",
    "subsidiary_sale",
    "investment_purchase",
    "loans_issued",
    "dividends_received",
    "interest_received",
    "deposits_movement",
)
CF_FINANCE = (
    "long_debt_cash",
    "short_debt_cash",
    "equity_issue",
    "lease_principal",
    "lease_interest_paid",
    "interest_paid",
    "dividends_paid",
)

LABELS = {
    "ppe": "Property, plant and equipment (including right-of-use)",
    "intangibles": "Intangible assets",
    "associates": "Investments in associates / joint venture",
    "investments": "Other investments",
    "ar_nc": "Non-current trade receivables",
    "ofa_nc": "Other non-current financial assets",
    "dta": "Deferred tax assets, net",
    "tax_assets": "Income tax assets, net",
    "inventories": "Inventories",
    "ar_current": "Current trade receivables",
    "cash": "Cash and cash equivalents",
    "other_bank": "Other bank balances",
    "loans": "Loans to related parties",
    "ofa_current": "Other current financial assets",
    "other_current_assets": "Other current assets",
    "share_capital": "Equity share capital",
    "premium": "Securities premium",
    "reserves": "Reserves and surplus",
    "application_money": "Share application money",
    "nci": "Non-controlling interests",
    "debt_nc": "Non-current borrowings",
    "lease_nc": "Non-current lease liabilities",
    "ap_nc": "Non-current trade payables",
    "ofl_nc": "Other non-current financial liabilities",
    "provisions_nc": "Non-current provisions",
    "other_liabilities_nc": "Other non-current liabilities",
    "debt_current": "Current borrowings",
    "lease_current": "Current lease liabilities",
    "ap_msme": "Trade payables: micro / small enterprises",
    "ap_other": "Trade payables: other creditors",
    "ofl_current": "Other current financial liabilities",
    "other_liabilities_current": "Other current liabilities",
    "provisions_current": "Current provisions",
    "tax_liabilities": "Current income tax liabilities, net",
    "revenue": "Revenue from operations",
    "fx_gain": "Foreign exchange gains",
    "other_income": "Other income",
    "total_income": "Total income",
    "cost_sales": "Cost of sales and services",
    "inventory_change": "Changes in inventories",
    "employees": "Employee benefits expense",
    "finance_cost": "Finance costs (borrowing interest + bank charges)",
    "da": "Depreciation and amortisation",
    "other_expenses": "Other expenses",
    "total_expenses": "Total expenses",
    "before_associates": "Profit before associates and tax",
    "associate_profit": "Share of profit of associates / joint venture, net",
    "before_exceptional": "Profit before exceptional items and tax",
    "exceptional": "Exceptional items (signed)",
    "pbt": "Profit before tax",
    "current_tax": "Current tax expense",
    "deferred_tax": "Deferred tax expense / (credit)",
    "net_income": "Profit for the year",
    "owners_profit": "Profit attributable to owners",
    "nci_profit": "Profit attributable to non-controlling interests",
    "oci_nonreclass": "OCI: items not subsequently reclassified, net of tax",
    "oci_reclass": "OCI: items subsequently reclassified, net of tax",
    "oci_owners": "OCI attributable to owners",
    "oci_nci": "OCI attributable to NCI",
    "total_comprehensive": "Total comprehensive income",
    "basic_eps": "Basic EPS (INR)",
    "diluted_eps": "Diluted EPS (INR)",
    "associates_adj": "Adjustment: associate profits",
    "unrealized_fx": "Unrealised forex adjustment",
    "bad_debt": "Bad debt / credit loss charge",
    "credit_writeback": "Credit loss provision reversal",
    "asset_sale_gain": "Adjustment: asset disposal gain",
    "subsidiary_sale_gain": "Adjustment: subsidiary disposal gain",
    "esop": "Share-based payment charge",
    "lease_interest": "Lease interest add-back",
    "borrowing_interest": "Borrowing interest add-back",
    "investment_income": "Investment income adjustment",
    "provision_contracts": "Provision: contract losses",
    "provision_employee": "Provision: employee benefits",
    "provision_damages": "Provision: liquidated damages",
    "provision_warranty": "Provision: warranty",
    "op_before_wc": "Operating profit before working capital",
    "wc_receivables": "Trade receivables movement",
    "wc_ofa": "Other financial assets movement",
    "wc_other_assets": "Other assets movement",
    "wc_inventory": "Inventories movement",
    "wc_payables": "Trade payables movement",
    "wc_ofl": "Other financial liabilities movement",
    "wc_other_liabilities": "Other liabilities movement",
    "wc_provisions": "Provisions movement / utilisation",
    "cash_generated": "Cash generated from operations",
    "taxes_paid": "Income taxes paid, net",
    "cfo": "Net cash from operating activities",
    "capex": "PPE / intangible purchases",
    "asset_sale": "Asset sale proceeds",
    "subsidiary_sale": "Subsidiary sale proceeds",
    "investment_purchase": "Investment purchases",
    "loans_issued": "Loans issued, net",
    "dividends_received": "Dividends received",
    "interest_received": "Interest received",
    "deposits_movement": "Deposits / other bank balances movement",
    "cfi": "Net cash from investing activities",
    "long_debt_cash": "Long-term borrowing cash movement",
    "short_debt_cash": "Short-term borrowing cash movement",
    "equity_issue": "Share issue proceeds",
    "lease_principal": "Lease principal cash movement",
    "lease_interest_paid": "Lease interest paid separately",
    "interest_paid": "Borrowing interest paid",
    "dividends_paid": "Dividends paid",
    "cff": "Net cash from financing activities",
    "cash_change": "Net change in cash",
    "cash_fx": "Exchange translation on cash",
    "opening_cash": "Opening cash and equivalents",
    "cash_held_for_sale": "Adjustment for cash held for sale",
    "closing_cash": "Closing cash and equivalents",
    "assets_nc": "Total non-current assets",
    "assets_current": "Total current assets",
    "assets": "TOTAL ASSETS",
    "equity": "Total equity",
    "liabilities_nc": "Total non-current liabilities",
    "liabilities_current": "Total current liabilities",
    "liabilities": "Total liabilities",
    "equity_liabilities": "TOTAL EQUITY AND LIABILITIES",
    "balance_residual": "Balance-sheet residual",
}

IS_ROWS = (
    "revenue",
    "fx_gain",
    "other_income",
    "total_income",
    *EXPENSES,
    "total_expenses",
    "before_associates",
    "associate_profit",
    "before_exceptional",
    "exceptional",
    "pbt",
    "current_tax",
    "deferred_tax",
    "net_income",
    "owners_profit",
    "nci_profit",
    "oci_nonreclass",
    "oci_reclass",
    "oci_owners",
    "oci_nci",
    "total_comprehensive",
    "basic_eps",
    "diluted_eps",
)
BS_ROWS = (
    *ASSETS_NC,
    "assets_nc",
    *ASSETS_C,
    "assets_current",
    "assets",
    *EQUITY,
    "equity",
    *LIAB_NC,
    "liabilities_nc",
    *LIAB_C,
    "liabilities_current",
    "liabilities",
    "equity_liabilities",
    "balance_residual",
)
CF_ROWS = (
    "pbt",
    *CF_ADJUSTMENTS,
    "op_before_wc",
    *CF_WC,
    "cash_generated",
    "taxes_paid",
    "cfo",
    *CF_INVEST,
    "cfi",
    *CF_FINANCE,
    "cff",
    "cash_change",
    "cash_fx",
    "opening_cash",
    "cash_held_for_sale",
    "closing_cash",
)


def balance_totals(b):
    for label, keys in (
        ("assets_nc", ASSETS_NC),
        ("assets_current", ASSETS_C),
        ("equity", EQUITY),
        ("liabilities_nc", LIAB_NC),
        ("liabilities_current", LIAB_C),
    ):
        b[label] = sum(b[key] for key in keys)
    b["assets"] = b["assets_nc"] + b["assets_current"]
    b["liabilities"] = b["liabilities_nc"] + b["liabilities_current"]
    b["equity_liabilities"] = b["equity"] + b["liabilities"]
    b["balance_residual"] = b["assets"] - b["equity_liabilities"]


def income_totals(s):
    s["total_income"] = s["revenue"] + s["fx_gain"] + s["other_income"]
    s["total_expenses"] = sum(s[k] for k in EXPENSES)
    s["before_associates"] = s["total_income"] - s["total_expenses"]
    s["before_exceptional"] = s["before_associates"] + s["associate_profit"]
    s["pbt"] = s["before_exceptional"] + s["exceptional"]
    s["total_comprehensive"] = s["net_income"] + s["oci_nonreclass"] + s["oci_reclass"]


def operating_nwc(b):
    # All other bank balances treated as operating collateral by explicit policy.
    return sum(b[k] for k in OP_ASSETS) + b["other_bank"] - sum(b[k] for k in OP_LIABS)
